server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/recommendationdb

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: recommendation-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
